### ISSUE TITLE
Problémy s ukoly 1

### ISSUE THREAD

**Issue by KristynaSodomkova** [KristynaSodomkova/python-012021#1]

**Comment by KristynaSodomkova** [comment]
@andywaltlova nejsem si jistá, jestli cesta u ukolu 4 je přes split?

**Comment by andywaltlova** [comment]
### 1. úkol :heavy_check_mark: 

- jdeš na to dobře, ale to co chceš po uživateli je string, kód balíku (`parcel_code`)a to asi není to co chceš porovnávat s  `True` nebo ` False` (string se považuje za True když je neprázdný, tedy jedině  prázdný  (`''`) string je False.
- ❗ Upozornění: pokud je proměnná typu bool, neměla by jsi psát `if promenna == True:` , preferovaná varianta je zkrátka napsat `if promenna:` , malý příklad:

```python
pravda = True
if pravda:
    print('Je to pravda!')
else:
    print('Neni to pravda!')'
```

Případně můžeš použít klíčové slovo `not`:
```python
pravda = True
if not pravda:  # negace False je True
    print('Neni to pravda!')
else:
    print('Je to pravda!')'
```

Je to stejné jako když kontroluješ například `if 2>3:` , což samozřejmě není pravda, ale za celým výrazem `2>3` si můžeš zkrátka představit `False` hodnotu :)


### 2. úkol :heavy_check_mark: 

- Perfektní, přesně takto by to mělo vypadat :)

### 3. úkol :heavy_check_mark: 

- Promiň ! jsem slepá! Samozřejmě je to v pořádku :)

### 4. úkol :heavy_check_mark: 

- EDIT: Ok
- HINT: Ideálně chceš for cyklem procházet string po znacích, a vždy k danému znaku vyhledat odpovídající hodnotu (pokud je znak mezera tak chces rovnou dat lomitko), s kontrolou toho jestli jsou písmenka ve slovníku se netrap, uvažuj že uživatel zadá text jen s písmen které máš ve slovníku k dispozici.

### 5. úkol :heavy_check_mark:
- 😱 Wow, nečekala bych že u někoho uvidím takto spojení slovníků, jestli jsi to takto vygooglila tak fakt paráda, je to pěkný způsob jak dva slovníky zkombinovat :)
- Kromě kombinace slovniků se daly použít podmínky a součet a nebo metoda get, která umí vracet i defaultní hodnotu, pokud klíč ve slovníku nenajde (`slovnik.get(klic,default)`) , pak můžeš zkrátka udělat součet z get metod z obou slovníků , default hodnoty by byli é pokud klic ve slovniku není.

---

Skvělá práce, budu se těšit na zbytek úkolů 👍

**Comment by KristynaSodomkova** [comment]
**Moc děkuju, Andy!** 
1 - přepracuju
3 - vždyť mi to funguje :D V zadání je počet volných místností, nikoliv jejich názvy (to mam zakomentovaný, jako variantu), u mě uživatel zadá číslo hodiny a vyplivne to počet volných místností - nebo to zadání špatně chápu?
4 - to je pro mě zatím masakr, nechápu, jak to udělat, aby to psalo i opakovaný klíče... budu študovat ještě z materiálů z předcházejícího workshopu a vezmu si tvé rady k srdci :)
2, 5 - díky, díky, díky, jó 👯‍♀️ 🥇 💯

**Comment by andywaltlova** [comment]
Upravila jsem, jsem slepá :) zmátly mě komentáře, sem si říkla, že to máš rozdělané :) Každopádně napraveno

**Comment by KristynaSodomkova** [comment]
Ahoj Andy, opravila jsem jedničku a mám hotovou 4 :)

**Comment by andywaltlova** [comment]
Ahoj, 
4. priklad super 👍 

U 1 pozor, je potreba nejdriv zkontrolovat jestli kod je ve slovniku (to tam momentalne mas), ale **to ze tam je automaticky neznamena ze je doruceny**, dorucenost je zavisla na hodnote, ktera k danemu kodu patri (ve slovniku True nebo False). 

Takze idealne chces akorat pridat vnorenou podminku, ktera kontroluje dorucenost podle hodnoty :) K tomu smerovala i moje rada, aby jsi se to pak nesnazila porovnavat jako `if baliky[parcel_code] == True: ` ale radeji jednoduse  `if baliky[parcel_code]: `

**Comment by KristynaSodomkova** [comment]
Nevím, jestli jsem to správně pochopila, ale zkusila jsem upravit program tak, aby zahlásil neznámý kód balíku...
Je to tak správně?

**Comment by andywaltlova** [comment]
Ahoj, 
super, tohle je úplně ideální řešení 👍 Primárně mi šlo o to ošklivé porovnávání bool hodnot, které jsi vymazala už minule. Jelikož si to ale nahradila jen kontrolou zda je kod ve slovniku nebo neni, tak to zas nekontrolovalo dorucenost. Ted to dela oboje a je to naprosto v poradku :)

Issue uzaviram a ukoly za prvni tyden povazuji za splnene :) (komentare jde pridavat porad)
