### ISSUE TITLE
Úkoly z lekce 10

### ISSUE THREAD

**Issue by KristynaSodomkova** [KristynaSodomkova/python-012021#10]
Ahoj Andy, snad jsem tu desítku dala nějak do kupy :)

**Comment by andywaltlova** [comment]
### 46 ✔️ 
- Uznám ti to, jen pozor u vztahu Zákaznik - Výpujčka, momentálně má zákazník vždy jen jednu výpujčku. Kdyby byl záznam o zákazníkovi u výpujčky, dávalo b yto větší smysl - jedna výpujčka patří jednomu zákazníkovi, zároveň těch výpujček se stejným zákazníkem může být více.
### 47 ✔️ 
- Super 👍 
### 48 ✔️ 
- Peknee, koukam ze mas pro kazde auto zvlast tabulku - coz je v pohode. Jen zadani asi predpokladalo ze bdue tabulka jedna a za kazde auto tam bude novy radek - pokud to mas schvalne jinak, protoze se ti to tak libi vic, tak to tak nech 👍 
### 49 ✔️ 
- Super
### 50 ✔️ 
- Nadhera, moc se mi libi, ze si myslela i na o kdyz se chci vratit zpet na hlavni strnaku - moc pekne intuitivne propojene :)

---
Takze celkove mas uz 50 bodu ! 🥳
