### ISSUE TITLE
ukoly_lekce_2

### ISSUE THREAD

**Issue by KristynaSodomkova** [KristynaSodomkova/python-012021#2]
Zatím zpracovaný úkol 6, 7, 8;  krev, pot a slzy; moc mě to baví :)

**Comment by andywaltlova** [comment]
Teda doufám, že to jsou jen slzy štěstí! 😄 

### 6. úkol :heavy_check_mark: 

- EDIT: po oprave ok
- Vypis statu je ok, druha cast zadani ale neni splnena uplne spravne
> Vytvoř program, který se uživatele zeptá na region, který ho zajímá. Následně projdi seznam a vypiš všechny státy, které leží v regionu. **Pokud program žádný stát pro daný region nenajde, vypiš text "Neznámý region"**

```python
if user_region not in staty:
    print("Neznámý region.")
```
-  staty je seznam slovniků, a ty se snazis kontrolovat jestli je v seznamu string, coz je vzdy false (protoze tam jsou prave jen slovniky). Takze i pri zadani existujiciho regionu napriklad Asie, je podminka splnena a print se provede (to nechceme).
- Je nekolik zpusobu jak se k tomu postavit, muzes si napriklad drzet nejakou bool promenou `region_found`, ktera je na zacatku `False` a jakmile se nejaky region objevi proste ji prepises na `True`, na konci programu pak udelas print podle stavu te promenne. Dalsi variantou by bylo napriklad regiony ukladat do seznamu a print provest jen pokud je list prazdny (tzn. zadny region se nenasel). 


### 7. úkol :heavy_check_mark: 

- Tohle je naprosto vporadku 👍 
- Na listy a slovniky si casem zvyknes, nejvice pouzivana kombinace, ktera existuje :)

### 8. úkol :heavy_check_mark: 

- EDIT: po oprave ok
- Tady to jeste nefunguje uplne korektne :)

Obecne poznamky:  
- if a elif v prvni funkci se klidne da spojit pomoci `or`, protoze v obou pripadech se ma stat stejna vec (vratit True) -> `if len(phone_number) == 9 or len(phone_number) == 13`
- definice funkci se vetsinou davaji do kodu nahoru a az pod ne se pise 'main' kod, ktery se vykonava, idealni by tedy bylo presunout funkci price na stejnou uroven jako verification, urcite by to pomohlo citelnosti kodu :)
- Intuitivne by mi davalo smysl kontrolovat delku retezce (radek 23) az ve funkci price, tedy predavat teto funkci string a at si snim dela co chce, jen at mi rekne vysledek :) Nevidim duvod mit to mimo, na nic jineho tu delku ani nepotrebujes. Ale to je jen moje doporuceni, ridit se tim nemusis.

Ohledne funkcnosti:
- Funkce verification je ok
- Vypocet ceny sms nevychazi (spatna prace s tou jednickou), pokud mam zpravu pod 180 znaku je to ok, ale napriklad zprava o 240 znacich by mela stat 6 kc, u tebe stoji porad 3Kc (ta jednicka tam zustane, nekde ji urcite potrebujes pricist 😉 )

---

U 6. prikladu opravit vypis kdyz region nen ive slovniku
U 8. prikladu opravit pocitani ceny sms a presunout funkci na stejnou uroven jako je verification. (ostatni poznamky jsou jen doporuceni)
