### ISSUE TITLE
úkoly z třetí lekce

### ISSUE THREAD

**Issue by KristynaSodomkova** [KristynaSodomkova/python-012021#3]
Ahoj, mám hotovou 11, 12, 13, 14

**Comment by KristynaSodomkova** [comment]
Ahoj, mám hotový úkol č. 15
U úkolu č. 12 byl problém vyřešen při konzultacích.
Moc děkuju za tipy!

**Comment by andywaltlova** [comment]
Ahoj,

### 15. úkol ✔️ 
- Super, neni co vytknout - skvele ze ti stacili k reseni tri datumy a nevytvarela si vsechny 4 :)

---

Týden 3 hotov ! 🎊
