### ISSUE TITLE
ukoly_lekce_5

### ISSUE THREAD

**Issue by KristynaSodomkova** [KristynaSodomkova/python-012021#5]
Ahoj Andy, udělala jsem zatím úkoly 21 - 24. Dost bojuju s tím zápisem, je to zatim strašný! Jinak doufám, že se máš hezky :)

**Comment by andywaltlova** [comment]
### 21 ✔️ 
- Super !
- V dobrovolne casti, kdyz chces prvni a posledni radek ( a zaroven posledni sloupec), da se klidne pouzit i zaporny index :)
    - `konec = int(twilio.iloc[-1,-1])`  -> hodnota v poslednim radku v poslednim sloupci
### 22 ✔️ 
- Pobavilo me ze si tu tabulku pojmenovala `mrtvoly` 🤣 - ale proc ne? je to vystizny 👍 
- Jak mas pormenou `vyber1`, tak klidne jsi to mohla spojit do jednoho volani `iloc` -> `mrtvoly.loc["Gevin Harlaw" : "Gillam", 'Death Year']` , protoze prvni argument jsou raadky a druhy sloupce (v tomt opripade jen jeden sloupec)
### 23 ✔️ 
- Dobree, hlavne jsem tu potrebovala videt ze umis spojovat vice podminek dohromady, jen mi nesedi nektere ty podminky s textovym zadanim, tak jen koukni jestli jsi se jen prekoukla :)
```py
# více než 1 mil naočkovaných dne 2021-03-10
naockovanych_pres_milion = staty[staty["total_vaccinations"] > 1_000_000] # tady chybi pripojit podminku s datumem (&)
print(naockovanych_pres_milion)
# kde za den naočkováno více než 1 mil nebo méně než 100 tis
extremni_hodnoty = staty[(staty["daily_vaccinations"] > 100_000) | (staty["daily_vaccinations"] < 100)] # tady mas jen jina cisla nez v zadani, 100 misto 100 000 a 100 000 misto 1 000 000 :)
print(extremni_hodnoty)
```
### 24 ✔️ 
- Super :)
- Ty zvlastni, hodne nizke hodnoty jsou asi nevyplnene hodnoty, ktere tam delaji neporadek :)

**Comment by KristynaSodomkova** [comment]
Ahoj Andy, dodělala jsem tu 25, ještě dneska kouknu na tu 23 (a moc děkuju za tipy!)

**Comment by andywaltlova** [comment]
### 25 ✔️ 
- Taky uplne v poradku :)
---
Tyden 5 tedy hotovo! :)
