### ISSUE TITLE
Ukoly 8 lekce

### ISSUE THREAD

**Issue by KristynaSodomkova** [KristynaSodomkova/python-012021#8]
Ahoj Andy, zasekla jsem se v úkolech z osmé lekce. Mám myslím hotový 36 a 37, ale když sem udělala úkol 38, tak při načtení do prohlížeče mi to hlásí chybu:
Page not found (404)
Request Method: | GET
-- | --
http://127.0.0.1:8000/
Using the URLconf defined in pujcovna.urls, Django tried these URL patterns, in this order:

admin/
katalog/
The empty path didn’t match any of these.
You’re seeing this error because you have DEBUG = True in your Django settings file. Change that to False, and Django will display a standard 404 page.

Myslím, že bych měla udělat tu migraci, jak jí vidím v kodim.cz, ale tu jsme myslím při lekci nedělali, tak nevím... Nebo tam mám někde nějakou chybu já?

**Comment by andywaltlova** [comment]
Ahoj 👋 

Pro snadnejsi kontrolu, mi do githubu commitni cely projekt - vse ve slozce `pujcovna` - takto nevidim jak to mas vytvorene.

Z toho, co si mi sem zkopirovala bych si tipla, ze mas spravne vytvorenou aplikaci katalog a mas pridanou i url adresu v `pujcovna/urls.py`, i sam django rika ze zna jen `/admin` a `/katalog`, takze zkus http://127.0.0.1:8000/katalog - to je ta adresa kde ty nase views maji byt :-)

**Comment by KristynaSodomkova** [comment]
No jo, díky! Tak ten katalog mi funguje, bohužel seznam ne. Ráda to sem přidám, ale nevím jak. To mám kliknout třeba pravým na projekt "pujcovna" a pak na git a "push"?

**Comment by andywaltlova** [comment]
Myslim si, ze by melo jit zaskrtnout v te karte commit vsechny soubory v te slozce (mozna rovnou i cela slozka), pres prave tlacitko by mohlo jit taky :) Muzem se na to zitra na lekci podivat.

**Comment by KristynaSodomkova** [comment]
comitnuté :)

**Comment by andywaltlova** [comment]
36, 37 ✔️ 
- Prvni dva ukoly jsou v poradku, vse funguje tak jak ma :)

38,39,40
- Jeste nehodnoceno - nevidim je zatim vypracovane :)

**Comment by KristynaSodomkova** [comment]
Ahoj Andy, omlouvám se za tak opožděné odpovědi, ale dopisuju závěrečnou práci na fakultu, do toho šílená realita rotační výuky ve škole a testování a další výmluvy :D Při minulé lekci jsem s Lídou provedla ten commit pro ty soubory, ale pořád mi nefunguje u té 38 vše, jak má, 
Ten první pohled se mi normálně načte, na adrese http://localhost:8000/katalog, ale nefunguje mi ten seznam http://localhost:8000/katalog/seznam/

Pomoc?

**Comment by KristynaSodomkova** [comment]
Zkusila jsem přidat do seznamu v pujcovna urls další položku seznamu, pořád nic :/

**Comment by KristynaSodomkova** [comment]
Tak už mi ta 38 funguje :)
ale fakt jsem to musela googlit, neviděla jsem v tom tu provázanost správně, jak jsme v lekci dělali jen jednu cestu

**Comment by andywaltlova** [comment]
Ahoj, mela jsem odpoved akorat rozepsanou, tak to sem jeste pridam :)

**V urls.py v projektu (pujcovna/urls.py) mas:**
```py
urlpatterns = [
    path('admin/', admin.site.urls), # toto je dobre
    path('katalog/', include("katalog.urls")), # toto je dobre
   # seznam uz sem davat nechces, protoze ten uz spada primo do aplikace katalog, proto bude az v urls.py v aplikaci
]
```
**V urls.py v aplikaci (katalog/urls.py) mas:**
```py
# urlpattern chces urcite definovat jen jednou (pokud je tam vickrat  vezme se ta posledni definovana)
urlpatterns = [
    # toto je ok, to je ta nase hlavni stranka, url  si muzes predstavit tak ze spojis tu cestu z urls z projektu s touto
    # tedy tato url je 'katalog/' (to uz sem nepises protoze je v urls v projektu ) + '' coz je porad jen 'katalog/'
    path('', views.IndexView.as_view(), name='index'),

    # No abys tu mela jeste ten seznam, musis vytvorit cestu tak aby vysledkem bylo 'katalog/seznam'
    # 'katalog/' (uz mas z hlavniho urls souboru, proto ji sem opet nepises) + '...' (tvoje dalsi cesta, uz to nebude prazdny string)
    path('...', views.SeznamView.as_view(), name='seznam')
]
```

Super ze si to vyresila sama! 👍

**Comment by KristynaSodomkova** [comment]
Děkuju za odpověď! Teď jsem to dotáhla celé :) A to vysvětlení mi naopak vždycky pomůže, abych si to srovnala v hlavě, díky ti :)

**Comment by andywaltlova** [comment]
Jinak tedy všechno funguje takže taky 5b ✔️  (podivala jsem se nejdriv na 9 ukol, kde nic nechybelo, takze je jasne ze i toto je v poradku 😄 )
